# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 20:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('stops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=8)),
            ],
        ),
    ]
